language: node_js
node_js:
  - "8"
sudo: required
services:
  - mongodb
env:
  - MONGODB_URI=mongodb://localhost/401-dvgram APP_SECRET=DeltaV
script:
  - |
    (for dir in $(find $PWD -maxdepth 2 -name package.json -printf "%h\n"); do
      cd $dir && npm install && npm run lint && npm test || exit 1
    done)
branches:
  only:
  - master
notifications:
  email: false
